language: python

python:
    - "3.5"
    - "3.6"

services:
    - redis-server

install:
    #- sudo add-apt-repository universe
    #- sudo apt install redis-server
    - pip install --upgrade pip setuptools wheel psutil pytest
    - pip install --default-timeout=2000 -q -e .
    - pip list
    - pip install autopep8 flake8
    - curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=1hzRxBhnkQA3lWLzTFdVuJ0t5Cj1IvVIU" > /dev/null
    - CODE="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
    - curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${CODE}&id=1hzRxBhnkQA3lWLzTFdVuJ0t5Cj1IvVIU" -o data/expert_epis/Pendulum-v0_2epis.pkl
script:
    - autopep8 -r . --diff --exit-code
    - flake8 .
    - pytest -x tests
sudo: required
